import { ensureDrop, error, presignedGet, withCors } from '../_lib.js';

export async function onRequestGet({ request, env, params }) {
  const id = params.id;
  if (id === 'text' || id?.startsWith('text-')) return withCors(error('Use a text download token generated by the API.', 404), request);

  const file = await env.DB.prepare(
    'SELECT f.id, f.name, f.object_key, f.content_type, f.drop_id FROM files f WHERE f.id = ?1'
  ).bind(id).first();
  if (!file) return withCors(error('Download not found.', 404), request);

  const checked = await ensureDrop(env, file.drop_id);
  if (checked.error) return withCors(error(checked.error, checked.error === 'Drop not found.' ? 404 : 410), request);

  try {
    const url = await presignedGet(env, file.object_key, file.name, 24 * 60 * 60);
    return new Response(null, {
      status: 302,
      headers: {
        Location: url,
        'Cache-Control': 'private, no-store',
        'Referrer-Policy': 'no-referrer'
      }
    });
  } catch (cause) {
    console.error(cause);
    return withCors(error('R2 signing is not configured yet.', 500), request);
  }
}
